Add scheduler
muprotocol/mu pull request #3
Opened 2022-09-12 18:29 UTC by Arshia001

2022-09-12 19:21 UTC, hamidrezakp commented on executor/src/infrastructure/config.rs
>          ("connection_manager.max_request_size_kb", "8192"),
and this should be `max_request_response_size_kb

2022-09-12 20:41 UTC, hamidrezakp approved these changes

2022-09-13 18:54 UTC, thepeak99 requested changes
Oh come on adding powershell makes it slower and bigger for no gain, its just a shell

2022-09-13 19:01 UTC, Arshia001 commented
> Oh come on adding powershell makes it slower and bigger for no gain, its just a shell

A good shell, and it comes with the full power of .NET. Besides, it's just a dev container, not the final product. Let's be inclusive, huh? 😄

2022-09-19 19:06 UTC, thepeak99 approved these changes

2022-09-20 10:42 UTC, merged