new design mudb, solve concurrency.
muprotocol/mu pull request #5
Opened 2022-09-19 20:51 UTC by MohsenNz

check it out, thank you.

2022-09-20 10:57 UTC, Arshia001 commented on executor/src/mu_stack/deploy.rs
> +    mudb::service::{DatabaseID, Service as DbService},
I don't like how this import is aliased every time. If we need to rename it, why not just name it `DbService`? And while we're at it, I think `DatabaseManager` is a better name.

2022-09-20 10:59 UTC, Arshia001 requested changes

2022-09-20 10:59 UTC, Arshia001 commented on executor/src/mudb/service.rs
> +#[derive(Debug, Clone)]
Why separate `Manager` and `Service`? The `Manager` could just as easily include all this functionality.

2022-09-20 10:59 UTC, Arshia001 commented on executor/src/mu_stack/deploy.rs
>      runtime::{
I don't like how this import is aliased every time. If we need to rename it, why not just name it `DbService`? And while we're at it, I think `DatabaseManager` is a better name.

2022-10-01 20:06 UTC, MohsenNz commented on executor/src/mudb/service.rs
> +#[derive(Debug, Clone)]
.

2022-10-01 20:08 UTC, MohsenNz commented on executor/src/mudb/service.rs
> +#[derive(Debug, Clone)]
.

2022-10-25 20:13 UTC, merged