Add test deployment scripts
muprotocol/mu pull request #8
Opened 2022-10-04 16:15 UTC by Arshia001

2022-10-11 08:53 UTC, hamidrezakp requested changes
why do you have this 2mb binary?
marketplace/scripts/test-stack/test-function.wasm

build it before tests.

Arshia: Done

2022-10-11 08:53 UTC, hamidrezakp commented on marketplace/scripts/cmd-deploy-empty.ts
> +    // Wait an additional 2 seconds for the node to become healthy
you can call `get_last_blockhash` which returns when there is at least one block.
and the node is healthy.
Current method might not work on slower systems like ci/cd

2022-10-25 11:42 UTC, Arshia001 commented
Remove tmux :D

2022-10-26 05:39 UTC, hamidrezakp commented
> Remove tmux :D

This is my lucky day :D thanks

2022-10-26 09:30 UTC, merged